inherited WC020FInputDataOreFM: TWC020FInputDataOreFM
  Width = 401
  Height = 245
  ExplicitWidth = 401
  ExplicitHeight = 245
  inherited IWFrameRegion: TIWRegion
    Width = 401
    Height = 245
    ExplicitWidth = 401
    ExplicitHeight = 245
    object edtOre: TmeIWEdit
      Left = 33
      Top = 141
      Width = 121
      Height = 21
      Css = 'input_hour_hhhhmm_neg width5chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtOre'
      SubmitOnAsyncEvent = True
      TabOrder = 0
      Text = 'edtOre'
    end
    object btnChiudi: TmeIWButton
      Left = 280
      Top = 166
      Width = 75
      Height = 25
      Css = 'pulsante'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Chiudi'
      Color = clBtnFace
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'btnConferma'
      TabOrder = 1
      OnClick = btnChiudiClick
      medpDownloadButton = False
    end
    object btnConferma: TmeIWButton
      Left = 280
      Top = 197
      Width = 75
      Height = 25
      Css = 'pulsante'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Conferma'
      Color = clBtnFace
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'btnConferma'
      TabOrder = 2
      OnClick = btnChiudiClick
      medpDownloadButton = False
    end
    object lblEtichettaOre: TmeIWLabel
      Left = 33
      Top = 119
      Width = 91
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblEtichettaOre'
      Caption = 'lblEtichettaOre'
      Enabled = True
    end
    object edtData: TmeIWEdit
      Left = 33
      Top = 81
      Width = 121
      Height = 21
      Css = 'input_data_dmy  width10chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtData'
      SubmitOnAsyncEvent = True
      TabOrder = 3
      OnAsyncChange = edtDataAsyncChange
      Text = 'edtData'
    end
    object lblEtichettaData: TmeIWLabel
      Left = 33
      Top = 59
      Width = 96
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblEtichettaData'
      Caption = 'lblEtichettaData'
      Enabled = True
    end
    object edtTextField: TmeIWEdit
      Left = 33
      Top = 197
      Width = 121
      Height = 21
      Css = 'width100pc'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtTextField'
      SubmitOnAsyncEvent = True
      TabOrder = 4
      Text = 'edtTextField'
    end
    object lblEtichettaTextField: TmeIWLabel
      Left = 33
      Top = 175
      Width = 125
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblEtichettaTextField'
      Caption = 'lblEtichettaTextField'
      Enabled = True
    end
    object lblEtichettaDataA: TmeIWLabel
      Left = 160
      Top = 59
      Width = 105
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblEtichettaDataA'
      Caption = 'lblEtichettaDataA'
      Enabled = True
    end
    object edtDataA: TmeIWEdit
      Left = 169
      Top = 81
      Width = 96
      Height = 21
      Css = 'input_data_dmy  width10chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtDataA'
      SubmitOnAsyncEvent = True
      TabOrder = 5
      OnAsyncChange = edtDataAAsyncChange
      Text = 'edtDataA'
    end
  end
end
