CREATE OR REPLACE FUNCTION M010F_GETDECORRENZAFINE(P_CODICE IN VARCHAR2, P_TIPO_MISSIONE IN VARCHAR2, P_DECORRENZA IN DATE) RETURN DATE IS
  RESULT DATE;
BEGIN
  SELECT NVL(MIN(M010.DECORRENZA)-1,TO_DATE('31123999','DDMMYYYY')) INTO RESULT
    FROM M010_PARAMETRICONTEGGIO M010
   WHERE M010.CODICE = P_CODICE
     AND M010.TIPO_MISSIONE = P_TIPO_MISSIONE
     AND M010.DECORRENZA > P_DECORRENZA;
  RETURN(RESULT);
END M010F_GETDECORRENZAFINE;
/