inherited WA099FUtilityDB: TWA099FUtilityDB
  Tag = 51
  Width = 834
  Height = 1086
  Title = '(WA099) Utility del Database'
  ExplicitWidth = 834
  ExplicitHeight = 1086
  DesignLeft = 8
  DesignTop = 8
  inherited btnSendFile: TmeIWButton
    TabOrder = 8
  end
  inherited edtAJAXFormID: TmeIWEdit
    TabOrder = 7
  end
  inherited btnShowElabError: TmeIWButton
    TabOrder = 5
  end
  object rgpSelezioneTabelle: TmeTIWAdvRadioGroup [9]
    Left = 16
    Top = 240
    Width = 344
    Height = 81
    Cursor = crAuto
    Css = 'groupbox'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    BorderColor = clWebBLACK
    BorderWidth = 0
    Caption = 'Selezione tabelle'
    CaptionFont.Color = clNone
    CaptionFont.Enabled = False
    CaptionFont.Size = 10
    CaptionFont.Style = []
    Columns = 2
    Editable = True
    FriendlyName = 'rgpSelezioneTabelle'
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    Items.Strings = (
      'Tabelle di'
      'Tabelle senza indici'
      'Tabelle senza chiave primaria'
      'Tabelle esterne al tablespace'
      'Tabelle con indici esterni al tablespace')
    ItemIndex = 0
    ScriptEvents = <>
    SubmitOnAsyncEvent = True
    TabOrder = 4
    OnClick = rgpSelezioneTabelleClick
  end
  object cgpTabelle: TmeTIWAdvCheckGroup [10]
    Left = 17
    Top = 327
    Width = 416
    Height = 45
    Cursor = crAuto
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    BorderColor = clNone
    BorderWidth = 0
    Caption = ''
    CaptionFont.Color = clNone
    CaptionFont.Size = 10
    CaptionFont.Style = []
    Columns = 2
    Editable = True
    FriendlyName = 'cgpTabelle'
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 6
    OnAsyncItemClick = cgpTabelleAsyncItemClick
    medpContextMenu = pmnAzioni
  end
  object memResult: TmeIWMemo [11]
    Left = 27
    Top = 918
    Width = 416
    Height = 58
    Cursor = crAuto
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    BGColor = clNone
    Editable = True
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    InvisibleBorder = False
    HorizScrollBar = False
    VertScrollBar = True
    Required = False
    TabOrder = 9
    SubmitOnAsyncEvent = True
    FriendlyName = 'memResult'
  end
  object btnTableNoParallel: TmeIWButton [12]
    Left = 483
    Top = 230
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Alter Table NoParallel'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 10
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnIndexNoParallel: TmeIWButton [13]
    Left = 483
    Top = 261
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Alter Index NoParallel'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 11
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnDeleteSchemaStats: TmeIWButton [14]
    Left = 483
    Top = 292
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Cancella statistiche schema'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 12
    OnClick = btnClick2
    medpDownloadButton = False
  end
  object btnGatherSchemaStats: TmeIWButton [15]
    Left = 483
    Top = 323
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Genera statistiche schema'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 13
    OnClick = btnClick2
    medpDownloadButton = False
  end
  object btnGatherTableStats: TmeIWButton [16]
    Left = 483
    Top = 354
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Genera statistiche tabelle'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 14
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnMoveTablespace: TmeIWButton [17]
    Left = 483
    Top = 385
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Move Tablespace'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 15
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnRebuildIndexes: TmeIWButton [18]
    Left = 483
    Top = 416
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Rebuild Indexes'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 16
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnDeleteStatistics: TmeIWButton [19]
    Left = 483
    Top = 495
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Delete Statistics'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 17
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnAnalyzeTable: TmeIWButton [20]
    Left = 483
    Top = 526
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Analyze Table'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 18
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnAnalyzeColumns: TmeIWButton [21]
    Left = 483
    Top = 557
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Analyze Columns'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 19
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnAnalyzeIndexes: TmeIWButton [22]
    Left = 483
    Top = 588
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Analyze Indexes'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 20
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnRicompilaInvalidi: TmeIWButton [23]
    Left = 404
    Top = 729
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Ricompila oggetti invalidi'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 21
    OnClick = btnRicompilaInvalidiClick
    medpDownloadButton = False
  end
  object btnRicompilaTutto: TmeIWButton [24]
    Left = 404
    Top = 698
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Ricompila tutti gli oggetti'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 22
    OnClick = btnRicompilaTuttoClick
    medpDownloadButton = False
  end
  object lblParametriCompilazione: TmeIWLabel [25]
    Left = 612
    Top = 640
    Width = 162
    Height = 16
    Cursor = crAuto
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Alignment = taLeftJustify
    BGColor = clNone
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    NoWrap = False
    ConvertSpaces = False
    HasTabOrder = False
    FriendlyName = 'lblParametriCompilazione'
    Caption = 'Parametri di compilazione'
    RawText = False
    Enabled = True
  end
  object chkDebug: TmeIWCheckBox [26]
    Left = 612
    Top = 662
    Width = 121
    Height = 21
    Cursor = crDefault
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Debug'
    Editable = True
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    SubmitOnAsyncEvent = True
    ScriptEvents = <>
    Style = stNormal
    TabOrder = 23
    Checked = False
    FriendlyName = 'chkDebug'
  end
  object chkCodeTypeInterpreted: TmeIWCheckBox [27]
    Left = 612
    Top = 689
    Width = 162
    Height = 21
    Cursor = crDefault
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Code type Interpreted'
    Editable = True
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    SubmitOnAsyncEvent = True
    ScriptEvents = <>
    Style = stNormal
    TabOrder = 24
    Checked = False
    FriendlyName = 'chkDebug'
  end
  object chkCodeTypeNative: TmeIWCheckBox [28]
    Left = 612
    Top = 716
    Width = 121
    Height = 21
    Cursor = crDefault
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Code type Native'
    Editable = True
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    SubmitOnAsyncEvent = True
    ScriptEvents = <>
    Style = stNormal
    TabOrder = 25
    Checked = False
    FriendlyName = 'chkDebug'
  end
  object chkReuseSettings: TmeIWCheckBox [29]
    Left = 612
    Top = 743
    Width = 121
    Height = 21
    Cursor = crDefault
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Reuse settings'
    Editable = True
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    SubmitOnAsyncEvent = True
    ScriptEvents = <>
    Style = stNormal
    TabOrder = 26
    Checked = False
    FriendlyName = 'chkDebug'
  end
  object btnRicompilaSelezionato: TmeIWButton [30]
    Left = 404
    Top = 667
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Ricompila oggetto selezionato'
    Enabled = False
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 27
    OnClick = btnRicompilaSelezionatoClick
    medpDownloadButton = False
  end
  object lblSelezionato: TmeIWLabel [31]
    Left = 612
    Top = 611
    Width = 0
    Height = 0
    Cursor = crAuto
    Css = 'intestazione font_grassetto'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Alignment = taLeftJustify
    BGColor = clNone
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    NoWrap = False
    ConvertSpaces = False
    HasTabOrder = False
    FriendlyName = 'lblParametriCompilazione'
    RawText = False
    Enabled = True
  end
  object lblOggettoSelezionato: TmeIWLabel [32]
    Left = 477
    Top = 611
    Width = 129
    Height = 16
    Cursor = crAuto
    Css = 'intestazione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Alignment = taLeftJustify
    BGColor = clNone
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    NoWrap = False
    ConvertSpaces = False
    HasTabOrder = False
    FriendlyName = 'lblParametriCompilazione'
    Caption = 'Oggetto selezionato:'
    RawText = False
    Enabled = True
  end
  object btnEsegui: TmeIWButton [33]
    Left = 499
    Top = 903
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Esegui'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnTableNoParallel'
    ScriptEvents = <>
    TabOrder = 28
    OnClick = btnEseguiClick
    medpDownloadButton = False
  end
  object rgpQuerySupporto: TmeTIWAdvRadioGroup [34]
    Left = 16
    Top = 791
    Width = 364
    Height = 81
    Cursor = crAuto
    Css = 'groupbox'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    BorderColor = clWebBLACK
    BorderWidth = 0
    Caption = 'Query di supporto'
    CaptionFont.Color = clNone
    CaptionFont.Enabled = False
    CaptionFont.Size = 10
    CaptionFont.Style = []
    Columns = 2
    Editable = True
    FriendlyName = 'rgpQuerySupporto'
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    Items.Strings = (
      'Situazione tablespace dati'
      'Situazione tablespace temporaneo'
      'Situazione data files'
      'Situazione tabelle di log')
    ItemIndex = 0
    ScriptEvents = <>
    SubmitOnAsyncEvent = True
    TabOrder = 29
  end
  object grdQuerySupporto: TmedpIWDBGrid [35]
    Left = 17
    Top = 604
    Width = 364
    Height = 150
    Cursor = crAuto
    Css = 'grid'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    BorderColors.Color = clWebWHITE
    BorderColors.Light = clWebWHITE
    BorderColors.Dark = clWebWHITE
    BGColor = clNone
    BorderSize = 0
    BorderStyle = tfVoid
    CellPadding = 0
    CellSpacing = 0
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FrameBuffer = 40
    Lines = tlAll
    OnRenderCell = grdQuerySupportoRenderCell
    UseFrame = False
    UseSize = False
    CellRenderOptions = []
    ScrollToCurrentRow = False
    Columns = <>
    DataSource = dcdsTablespace
    FooterRowCount = 0
    FriendlyName = 'grdQuerySupporto'
    FromStart = True
    HighlightColor = clNone
    HighlightRows = False
    Options = [dgShowTitles]
    RefreshMode = rmAutomatic
    RowLimit = 0
    RollOver = False
    RowClick = True
    RollOverColor = clNone
    RowHeaderColor = clNone
    RowAlternateColor = clNone
    RowCurrentColor = clNone
    TabOrder = -1
    medpTipoContatore = 'P'
    medpRighePagina = -1
    medpBrowse = True
    medpRowSelect = True
    medpEditMultiplo = False
    medpFixedColumns = 0
    medpComandiCustom = False
    medpComandiEdit = False
    medpComandiInsert = False
    medpComandoDelete = False
  end
  object imgDeselezionaTutto: TmeIWImageFile [36]
    Left = 323
    Top = 285
    Width = 22
    Height = 21
    Cursor = crAuto
    Hint = 'Deseleziona tutto'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    BorderOptions.Color = clNone
    BorderOptions.Width = 0
    ScriptEvents = <>
    TabOrder = -1
    UseSize = False
    OnAsyncClick = imgDeselezionaTuttoAsyncClick
    Cacheable = True
    FriendlyName = 'IWImageFile1'
    ImageFile.Filename = 'img\btnUncheckAll.png'
    medpDownloadButton = False
  end
  object imgInvertiSelezione: TmeIWImageFile [37]
    Left = 351
    Top = 285
    Width = 22
    Height = 21
    Cursor = crAuto
    Hint = 'Inverti selezione'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    BorderOptions.Color = clNone
    BorderOptions.Width = 0
    ScriptEvents = <>
    TabOrder = -1
    UseSize = False
    OnAsyncClick = imgInvertiSelezioneAsyncClick
    Cacheable = True
    FriendlyName = 'IWImageFile1'
    ImageFile.Filename = 'img\btnInvertSelect.png'
    medpDownloadButton = False
  end
  object imgSelezionaTutto: TmeIWImageFile [38]
    Left = 295
    Top = 285
    Width = 22
    Height = 21
    Cursor = crAuto
    Hint = 'Seleziona tutto'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    BorderOptions.Color = clNone
    BorderOptions.Width = 0
    ScriptEvents = <>
    TabOrder = -1
    UseSize = False
    OnAsyncClick = imgSelezionaTuttoAsyncClick
    Cacheable = True
    FriendlyName = 'imgSelezionaTutto'
    ImageFile.Filename = 'img\btnCheckAll.png'
    medpDownloadButton = False
  end
  object trvOggettiDB: TmeIWTreeView [39]
    Left = 17
    Top = 378
    Width = 364
    Height = 200
    Cursor = crAuto
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    FriendlyName = 'trvOggettiDB'
    Font.Color = clNone
    Font.Size = 10
    Font.Style = []
    AutoIndent = True
    UseItemImages = True
    TreeViewImagesWidth = 16
    TreeViewImagesHeigth = 16
    UseFrame = False
    DoServerSidePlusMinus = False
    Items = <>
  end
  object btnShrinkTable: TmeIWButton [40]
    Left = 483
    Top = 447
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Shrink Table'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnShrinkTable'
    ScriptEvents = <>
    TabOrder = 30
    OnClick = btnClick
    medpDownloadButton = False
  end
  object btnV430Storico: TmeIWButton [41]
    Left = 404
    Top = 636
    Width = 169
    Height = 25
    Cursor = crAuto
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Creazione V430_STORICO'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnV430Storico'
    ScriptEvents = <>
    TabOrder = 32
    OnClick = btnV430StoricoClick
    medpDownloadButton = False
  end
  object btnCopiaTestoQuery: TmeIWButton [42]
    Left = 499
    Top = 951
    Width = 169
    Height = 25
    Cursor = crAuto
    Hint = 'Copia il testo della query selezionata negli appunti'
    Css = 'pulsante'
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    Caption = 'Copia testo query'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnCopiaTestoQuery'
    ScriptEvents = <>
    TabOrder = 33
    OnClick = btnCopiaTestoQueryClick
    medpDownloadButton = False
  end
  inherited TemplateProcessor: TIWTemplateProcessorHTML
    Left = 215
  end
  object JQuery: TIWJQueryWidget
    Enabled = True
    Left = 432
    Top = 160
  end
  object dcdsTablespace: TDataSource
    DataSet = cdsTablespace
    Left = 328
    Top = 632
  end
  object cdsTablespace: TClientDataSet
    Aggregates = <>
    Params = <>
    Left = 240
    Top = 632
  end
  object pmnAzioni: TPopupMenu
    Left = 240
    Top = 312
    object Selezionatutto1: TMenuItem
      Caption = 'Seleziona tutto'
      Hint = 'checkAll'
      OnClick = Selezionatutto1Click
    end
    object Deselezionatutto1: TMenuItem
      Caption = 'Deseleziona tutto'
      Hint = 'checkNone'
      OnClick = Deselezionatutto1Click
    end
    object Invertiselezione1: TMenuItem
      Caption = 'Inverti selezione'
      Hint = 'checkInvert'
      OnClick = Invertiselezione1Click
    end
  end
end
