inherited WA146FFotoDipendenteDettFM: TWA146FFotoDipendenteDettFM
  inherited IWFrameRegion: TIWRegion
    object rgpRisorsa: TmeIWRadioGroup
      Left = 48
      Top = 74
      Width = 185
      Height = 37
      Cursor = crDefault
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      OnClick = rgpRisorsaClick
      SubmitOnAsyncEvent = True
      RawText = False
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'rgpRisorsa'
      ItemIndex = -1
      Items.Strings = (
        'Database'
        'Percorso')
      Layout = glHorizontal
      TabOrder = 0
    end
    object edtPercorso: TmeIWDBEdit
      Left = 216
      Top = 74
      Width = 153
      Height = 37
      Css = 'width50chr'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtPercorso'
      SubmitOnAsyncEvent = True
      TabOrder = 1
      AutoEditable = True
      DataField = 'FILE_FOTO'
      PasswordPrompt = False
    end
    object Image1: TmeIWImage
      Left = 48
      Top = 128
      Width = 321
      Height = 177
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPadding = False
      BorderOptions.Width = 0
      TabOrder = -1
      UseSize = False
      FriendlyName = 'Image1'
      TransparentColor = clNone
      JpegOptions.CompressionQuality = 90
      JpegOptions.Performance = jpBestSpeed
      JpegOptions.ProgressiveEncoding = False
      JpegOptions.Smoothing = True
    end
    object lblDimensione: TmeIWLabel
      Left = 33
      Top = 328
      Width = 0
      Height = 0
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDimensione'
      Enabled = True
    end
  end
end
