inherited WA145FComVisiteFiscali: TWA145FComVisiteFiscali
  Tag = 66
  Width = 788
  Height = 920
  ExplicitWidth = 788
  ExplicitHeight = 920
  DesignLeft = 8
  DesignTop = 8
  inherited grdStatusBar: TmedpIWStatusBar
    Top = 121
    ExplicitTop = 121
  end
  inherited btnShowElabError: TmeIWButton
    Left = 160
    Top = 90
    ExplicitLeft = 160
    ExplicitTop = 90
  end
  object grdTabDetail: TmedpIWTabControl [9]
    Left = 16
    Top = 152
    Width = 313
    Height = 25
    Css = 'gridTabControl'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    BorderColors.Color = clWebWHITE
    BorderColors.Light = clWebWHITE
    BorderColors.Dark = clWebWHITE
    BGColor = clNone
    BorderSize = 0
    BorderStyle = tfVoid
    CellPadding = 0
    CellSpacing = 0
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FrameBuffer = 40
    Lines = tlNone
    UseFrame = False
    UseSize = False
    HeaderRowCount = 0
    CellRenderOptions = []
    FriendlyName = 'grdTabDetail'
    ColumnCount = 1
    RowCount = 1
    ShowEmptyCells = True
    ShowInvisibleRows = True
    ScrollToCurrentRow = False
    CssTabHeaders = 'medpTabControl'
  end
  object btnEsegui: TmedpIWImageButton [10]
    Left = 195
    Top = 862
    Width = 122
    Height = 27
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    BorderOptions.Width = 0
    TabOrder = -1
    UseSize = False
    OnClick = btnEseguiClick
    Cacheable = True
    FriendlyName = 'btnEsegui'
    ImageFile.URL = 'img/btnEsegui.png'
    medpDownloadButton = False
    Caption = 'Esegui'
  end
  object btnGeneraPDF: TmedpIWImageButton [11]
    Left = 29
    Top = 861
    Width = 122
    Height = 28
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    BorderOptions.Width = 0
    TabOrder = -1
    UseSize = False
    OnClick = btnGeneraPDFClick
    Cacheable = True
    FriendlyName = 'btnGeneraPDF'
    ImageFile.URL = 'img/btnPdf.png'
    medpDownloadButton = False
    Caption = 'Stampa in PDF'
  end
  object btnEsenzioni: TmedpIWImageButton [12]
    Left = 371
    Top = 862
    Width = 122
    Height = 28
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    BorderOptions.Width = 0
    TabOrder = -1
    UseSize = False
    OnClick = btnEsenzioniClick
    Cacheable = True
    FriendlyName = 'btnEsenzioni'
    ImageFile.URL = 'img/btnCheck.png'
    medpDownloadButton = False
    Caption = 'Esenzioni'
  end
  object WA145EsenzioniRG: TmeIWRegion [13]
    Left = 19
    Top = 767
    Width = 636
    Height = 88
    RenderInvisibleControls = False
    BorderOptions.NumericWidth = 1
    BorderOptions.BorderWidth = cbwNumeric
    BorderOptions.Style = cbsSolid
    BorderOptions.Color = clNone
    LayoutMgr = WA145EsenzioniRGTemplate
    object grdEsenzioni: TmedpIWDBGrid
      Left = 37
      Top = 14
      Width = 300
      Height = 43
      Css = 'grid'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderBorder = False
      BorderColors.Color = clWebWHITE
      BorderColors.Light = clWebWHITE
      BorderColors.Dark = clWebWHITE
      BGColor = clNone
      BorderSize = 0
      BorderStyle = tfVoid
      Caption = 'grdEsenzioni'
      CellPadding = 0
      CellSpacing = 0
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FrameBuffer = 40
      Lines = tlAll
      Summary = 'Elenco esenzioni'
      UseFrame = False
      UseSize = False
      HeaderRowCount = 0
      CellRenderOptions = []
      ScrollToCurrentRow = False
      Columns = <>
      FooterRowCount = 0
      FriendlyName = 'grdEsenzioni'
      FromStart = True
      HighlightColor = clNone
      HighlightRows = False
      Options = [dgShowTitles]
      RefreshMode = rmAutomatic
      RowLimit = 0
      RollOver = False
      RowClick = True
      RollOverColor = clNone
      RowHeaderColor = clNone
      RowAlternateColor = clNone
      RowCurrentColor = clNone
      TabOrder = -1
      medpContextMenu = pmnGrdTabella
      medpTipoContatore = 'P'
      medpRighePagina = -1
      medpBrowse = True
      medpRowSelect = True
      medpEditMultiplo = False
      medpFixedColumns = 0
      medpComandiCustom = False
      medpComandiEdit = False
      medpComandiInsert = False
      medpComandoDelete = False
      OnAfterCaricaCDS = grdEsenzioniAfterCaricaCDS
      OnDataSet2Componenti = grdEsenzioniDataSet2Componenti
      OnComponenti2DataSet = grdEsenzioniComponenti2DataSet
      OnmedpStatoChange = grdEsenzionimedpStatoChange
      OnBeforeModifica = grdEsenzioniBeforeModifica
    end
    object rgpFiltro: TmeTIWAdvRadioGroup
      Left = 370
      Top = 3
      Width = 223
      Height = 65
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderBorder = False
      BorderColor = clWebTransparent
      BorderWidth = 0
      Caption = ''
      CaptionFont.Color = clNone
      CaptionFont.Enabled = False
      CaptionFont.Size = 10
      CaptionFont.Style = []
      Columns = 2
      Editable = True
      FriendlyName = 'rgpFiltro'
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      Items.Strings = (
        'Dipendenti non esentati o esentati nel giorno'
        'Entrambi'
        'Dipendenti esentati nei giorni precedenti'
        'Cancellazioni non esentate o esentate nel giorno')
      ItemIndex = 0
      SubmitOnAsyncEvent = True
      TabOrder = 37
      OnClick = rgpFiltroClick
    end
  end
  object WA145VisiteFiscaliRG: TmeIWRegion [14]
    Left = 3
    Top = 183
    Width = 649
    Height = 578
    RenderInvisibleControls = False
    BorderOptions.NumericWidth = 1
    BorderOptions.BorderWidth = cbwNumeric
    BorderOptions.Style = cbsSolid
    BorderOptions.Color = clNone
    LayoutMgr = WA145VisiteFiscaliRGTemplate
    object edtDataElaborazione: TmeIWEdit
      Left = 13
      Top = 32
      Width = 84
      Height = 21
      Css = 'input_data_dmy width10chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtDataElaborazione'
      SubmitOnAsyncEvent = True
      TabOrder = 7
      Text = 'edtDataElaborazione'
    end
    object lblDataElaborazione: TmeIWLabel
      Left = 13
      Top = 10
      Width = 113
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDataElaborazione'
      Caption = 'Data elaborazione'
      Enabled = True
    end
    object cmbMedicineLegali: TMedpIWMultiColumnComboBox
      Left = 136
      Top = 32
      Width = 121
      Height = 21
      Css = 'medpMultiColumnCombo'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'cmbMedicineLegali'
      SubmitOnAsyncEvent = True
      TabOrder = 8
      OnAsyncChange = cmbMedicineLegaliAsyncChange
      PopUpHeight = 15
      PopUpWidth = 0
      Text = ''
      ColCount = 2
      Items = <>
      ColumnTitles.Visible = False
      medpAutoResetItems = True
      CssInputText = 'width10chr'
      LookupColumn = 0
      CodeColumn = 0
    end
    object lblMedicineLegali: TmeIWLabel
      Left = 144
      Top = 3
      Width = 96
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblMedicineLegali'
      Caption = 'Medicina legale'
      Enabled = True
    end
    object lblDescMedicineLegali: TmeIWLabel
      Left = 280
      Top = 16
      Width = 135
      Height = 16
      Css = 'descrizione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDescMedicineLegali'
      Caption = 'lblDescMedicineLegali'
      Enabled = True
    end
    object lblRegistrazioni: TmeIWLabel
      Left = 16
      Top = 59
      Width = 165
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblRegistrazioni'
      Caption = 'Registrazioni da elaborare'
      Enabled = True
    end
    object chkIns: TmeIWCheckBox
      Left = 16
      Top = 81
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Inserimento'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 9
      Checked = False
      FriendlyName = 'chkIns'
    end
    object chkProl: TmeIWCheckBox
      Left = 16
      Top = 100
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Prolungamento'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 10
      OnAsyncClick = chkProlAsyncClick
      Checked = False
      FriendlyName = 'chkProl'
    end
    object chkSoloCont: TmeIWCheckBox
      Left = 16
      Top = 120
      Width = 212
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Solo tipo certificato continuazione'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 11
      Checked = False
      FriendlyName = 'chkSoloCont'
    end
    object chkCanc: TmeIWCheckBox
      Left = 16
      Top = 139
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Cancellazione'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 12
      Checked = False
      FriendlyName = 'chkCanc'
    end
    object chkAggiorna: TmeIWCheckBox
      Left = 26
      Top = 166
      Width = 202
      Height = 21
      Hint = 
        'Selezionare per rendere effettiva la comunicazione delle assenze' +
        ' nella data indicata'
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Aggiorna data comunicazione'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 13
      OnAsyncClick = chkOpzioniAsyncClick
      Checked = False
      FriendlyName = 'chkAggiorna'
    end
    object chkAnnulla: TmeIWCheckBox
      Left = 26
      Top = 184
      Width = 200
      Height = 21
      Hint = 'Selezionare per annullare una comunicazione'
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Annulla ultima comunicazione'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 14
      OnAsyncClick = chkOpzioniAsyncClick
      Checked = False
      FriendlyName = 'chkAnnulla'
    end
    object lblOpzioniEsenzione: TmeIWLabel
      Left = 240
      Top = 59
      Width = 128
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblOpzioniEsenzione'
      Caption = 'Opzioni di esenzione'
      Enabled = True
    end
    object chkEsenzioneAutomatica: TmeIWCheckBox
      Left = 232
      Top = 81
      Width = 183
      Height = 21
      Hint = 
        'Selezionare per includere in stampa i periodi di assenza gi'#224' com' +
        'unicati'
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Esenzione automatica '
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 15
      Checked = False
      FriendlyName = 'chkEsenzioneAutomatica'
    end
    object lblNumeroMinimoEventi: TmeIWLabel
      Left = 234
      Top = 108
      Width = 157
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblNumeroMinimoEventi'
      Caption = 'Numero minimo di eventi'
      Enabled = True
    end
    object edtNumeroMinimoEventi: TmeIWEdit
      Left = 386
      Top = 104
      Width = 49
      Height = 21
      Css = 'input_num_nnn width3chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtNumeroMinimoEventi'
      SubmitOnAsyncEvent = True
      TabOrder = 16
      Text = 'edtNumeroMinimoEventi'
    end
    object lblMaxGiorniContinuativi: TmeIWLabel
      Left = 236
      Top = 131
      Width = 144
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblMaxGiorniContinuativi'
      Caption = 'Max giorni continuativi '
      Enabled = True
    end
    object edtMaxGiorniContinuativi: TmeIWEdit
      Left = 386
      Top = 130
      Width = 49
      Height = 21
      Css = 'input_num_nnn width3chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtMaxGiorniContinuativi'
      SubmitOnAsyncEvent = True
      TabOrder = 17
      Text = 'edtMaxGiorniContinuativi'
    end
    object lblMesiVerificaEventi: TmeIWLabel
      Left = 234
      Top = 152
      Width = 119
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblMesiVerificaEventi'
      Caption = 'Mesi verifica eventi'
      Enabled = True
    end
    object edtMesiVerificaEventi: TmeIWEdit
      Left = 386
      Top = 152
      Width = 49
      Height = 21
      Css = 'input_num_nnn width3chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtMesiVerificaEventi'
      SubmitOnAsyncEvent = True
      TabOrder = 18
      Text = 'edtMesiVerificaEventi'
    end
    object lblOpzioniStampa: TmeIWLabel
      Left = 464
      Top = 59
      Width = 112
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblOpzioniStampa'
      Caption = 'Opzioni di stampa'
      Enabled = True
    end
    object rgpTipoStampa: TmeTIWAdvRadioGroup
      Left = 467
      Top = 81
      Height = 40
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderBorder = False
      BorderColor = clWebTransparent
      BorderWidth = 0
      Caption = 'Tipo'
      CaptionFont.Color = clNone
      CaptionFont.Enabled = False
      CaptionFont.Size = 10
      CaptionFont.Style = []
      Columns = 2
      Editable = True
      FriendlyName = 'rgpTipoStampa'
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      Items.Strings = (
        'Elenco'
        'Individuale')
      ItemIndex = 0
      Layout = glHorizontal
      SubmitOnAsyncEvent = True
      TabOrder = 19
      OnAsyncClick = rgpTipoStampaAsyncClick
    end
    object chkPeriodiComunicati: TmeIWCheckBox
      Left = 466
      Top = 112
      Width = 121
      Height = 21
      Hint = 
        'Selezionare per includere in stampa i periodi di assenza gi'#224' com' +
        'unicati'
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Includi periodi di assenza gi'#224' comunicati'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 20
      OnAsyncClick = chkOpzioniAsyncClick
      Checked = False
      FriendlyName = 'chkPeriodiComunicati'
    end
    object chkFiltroDataComun: TmeIWCheckBox
      Left = 466
      Top = 139
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Filtra per data comunicazione'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 21
      OnAsyncClick = chkOpzioniAsyncClick
      Checked = False
      FriendlyName = 'chkFiltroDataComun'
    end
    object edtDataDa: TmeIWEdit
      Left = 467
      Top = 166
      Width = 81
      Height = 21
      Css = 'input_data_dmy width10chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtDataDa'
      SubmitOnAsyncEvent = True
      TabOrder = 22
      OnAsyncChange = edtDataDaAsyncChange
      Text = 'edtDataDa'
    end
    object edtDataA: TmeIWEdit
      Left = 464
      Top = 193
      Width = 81
      Height = 21
      Css = 'input_data_dmy width10chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtDataA'
      SubmitOnAsyncEvent = True
      TabOrder = 23
      Text = 'edtDataA'
    end
    object lblDataDa: TmeIWLabel
      Left = 441
      Top = 171
      Width = 16
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDataDa'
      Caption = 'Da'
      Enabled = True
    end
    object lblDataA: TmeIWLabel
      Left = 450
      Top = 193
      Width = 8
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDataA'
      Caption = 'A'
      Enabled = True
    end
    object chkStampaAssMal: TmeIWCheckBox
      Left = 368
      Top = 215
      Width = 137
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Stampa Ass.Malattia'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 24
      Checked = False
      FriendlyName = 'chkStampaAssMal'
    end
    object chkNote: TmeIWCheckBox
      Left = 511
      Top = 218
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Stampa note'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 25
      Checked = False
      FriendlyName = 'chkNote'
    end
    object lblDatiAnagrafici: TmeIWLabel
      Left = 26
      Top = 223
      Width = 163
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDatiAnagrafici'
      Caption = 'Dati anagrafici di dettaglio'
      Enabled = True
    end
    object lstElementiDettaglio: TmeIWListbox
      Left = 26
      Top = 280
      Width = 183
      Height = 33
      Css = 'width40chr height15'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      UseSize = False
      OnAsyncDoubleClick = lstElementiDettaglioAsyncDoubleClick
      TabOrder = 26
      NonEditableAsLabel = True
      FriendlyName = 'lstElementiDettaglio'
      medpContextMenu = pmnElemDettaglio
      NoSelectionText = ' '
    end
    object lblDisponibili: TmeIWLabel
      Left = 35
      Top = 258
      Width = 119
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDisponibili'
      Caption = 'Elementi disponibili'
      Enabled = True
    end
    object lblSelezionati: TmeIWLabel
      Left = 416
      Top = 258
      Width = 124
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblSelezionati'
      Caption = 'Elementi selezionati'
      Enabled = True
    end
    object imgRimuovi: TmeIWImageFile
      Left = 240
      Top = 285
      Width = 22
      Height = 21
      Hint = 'Rimuovi'
      HelpType = htKeyword
      HelpKeyword = '1615'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BorderOptions.Width = 0
      TabOrder = -1
      UseSize = False
      OnAsyncClick = imgRimuoviAsyncClick
      Cacheable = True
      FriendlyName = 'imgRimuovi'
      ImageFile.Filename = 'img\btnSx.png'
      medpDownloadButton = False
    end
    object imgAggiungi: TmeIWImageFile
      Left = 240
      Top = 258
      Width = 22
      Height = 21
      Hint = 'Aggiungi'
      HelpType = htKeyword
      HelpKeyword = '1615'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BorderOptions.Width = 0
      TabOrder = -1
      UseSize = False
      OnAsyncClick = imgAggiungiAsyncClick
      Cacheable = True
      FriendlyName = 'imgAccedi'
      ImageFile.Filename = 'img\btnDx.png'
      medpDownloadButton = False
    end
    object chkLogo: TmeIWCheckBox
      Left = 37
      Top = 344
      Width = 172
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Larghezza logo (pixel):'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 27
      OnAsyncClick = chkLogoAsyncClick
      Checked = False
      FriendlyName = 'chkLogo'
    end
    object edtLogoLarg: TmeIWEdit
      Left = 205
      Top = 336
      Width = 121
      Height = 21
      Css = 'input_num_nnn width3chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtLogoLarg'
      SubmitOnAsyncEvent = True
      TabOrder = 28
      Text = 'edtLogoLarg'
    end
    object chkNumProt: TmeIWCheckBox
      Left = 37
      Top = 371
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Num. protocollo:'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 29
      OnAsyncClick = chkNumProtAsyncClick
      Checked = False
      FriendlyName = 'chkNumProt'
    end
    object edtNumProt: TmeIWEdit
      Left = 192
      Top = 371
      Width = 121
      Height = 21
      Css = 'width5chr'
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtNumProt'
      SubmitOnAsyncEvent = True
      TabOrder = 30
      Text = 'edtNumProt'
    end
    object chkLuogo: TmeIWCheckBox
      Left = 337
      Top = 376
      Width = 121
      Height = 21
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Luogo di stampa:'
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      SubmitOnAsyncEvent = True
      Style = stNormal
      TabOrder = 31
      OnAsyncClick = chkLuogoAsyncClick
      Checked = False
      FriendlyName = 'chkLuogo'
    end
    object edtLuogo: TmeIWEdit
      Left = 464
      Top = 376
      Width = 121
      Height = 21
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'edtLuogo'
      SubmitOnAsyncEvent = True
      TabOrder = 32
      Text = 'edtLuogo'
    end
    object lstElementiDettaglioSelezionati: TmeIWListbox
      Left = 368
      Top = 280
      Width = 183
      Height = 33
      Css = 'width40chr height15'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      UseSize = False
      OnAsyncDoubleClick = lstElementiDettaglioSelezionatiAsyncDoubleClick
      TabOrder = 33
      NonEditableAsLabel = True
      FriendlyName = 'lstElementiDettaglio'
      medpContextMenu = pmnElemDettaglio
      NoSelectionText = ' '
    end
    object memDato1: TmeIWMemo
      Left = 192
      Top = 398
      Width = 121
      Height = 55
      Css = 'width70chr height5'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BGColor = clNone
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      InvisibleBorder = False
      HorizScrollBar = False
      VertScrollBar = True
      Required = False
      TabOrder = 34
      SubmitOnAsyncEvent = True
      FriendlyName = 'memDato1'
    end
    object memDato2: TmeIWMemo
      Left = 192
      Top = 454
      Width = 121
      Height = 55
      Css = 'width70chr height5'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BGColor = clNone
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      InvisibleBorder = False
      HorizScrollBar = False
      VertScrollBar = True
      Required = False
      TabOrder = 35
      SubmitOnAsyncEvent = True
      FriendlyName = 'memDato1'
    end
    object memFirma: TmeIWMemo
      Left = 192
      Top = 515
      Width = 121
      Height = 55
      Css = 'width70chr height5'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BGColor = clNone
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      InvisibleBorder = False
      HorizScrollBar = False
      VertScrollBar = True
      Required = False
      TabOrder = 36
      SubmitOnAsyncEvent = True
      FriendlyName = 'memDato1'
    end
    object lblDato1: TmeIWLabel
      Left = 87
      Top = 398
      Width = 85
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDato1'
      Caption = 'Dato libero 1:'
      Enabled = True
    end
    object lblDato2: TmeIWLabel
      Left = 87
      Top = 456
      Width = 85
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDato2'
      Caption = 'Dato libero 2:'
      Enabled = True
    end
    object lblFirma: TmeIWLabel
      Left = 87
      Top = 520
      Width = 41
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblFirma'
      Caption = 'Firma:'
      Enabled = True
    end
  end
  inherited AJNInizioElaborazione: TIWAJAXNotifier
    Left = 616
    Top = 80
  end
  inherited AJNElaboraElemento: TIWAJAXNotifier
    Left = 616
    Top = 136
  end
  inherited AJNMessaggioElaborazione: TIWAJAXNotifier
    Left = 616
    Top = 392
  end
  inherited AJNElementoSuccessivo: TIWAJAXNotifier
    Left = 616
    Top = 200
  end
  inherited AJNFineCicloElaborazione: TIWAJAXNotifier
    Left = 616
    Top = 256
  end
  inherited AJNElaborazioneTerminata: TIWAJAXNotifier
    Left = 616
    Top = 320
  end
  object WA145VisiteFiscaliRGTemplate: TIWTemplateProcessorHTML
    TagType = ttIntraWeb
    Templates.Default = 'WA145VisiteFiscaliRG.html'
    Left = 448
    Top = 192
  end
  object WA145EsenzioniRGTemplate: TIWTemplateProcessorHTML
    TagType = ttIntraWeb
    Templates.Default = 'WA145EsenzioniRG.html'
    Left = 576
    Top = 784
  end
  object JQuery: TIWJQueryWidget
    Enabled = True
    Left = 352
    Top = 16
  end
  object DCOMConnection: TDCOMConnection
    ServerGUID = '{ABA07A35-402E-4181-9C3A-9B6ECE4C791E}'
    ServerName = 'B028PPrintServer_COM.B028PrintServer'
    ComputerName = 'localhost'
    Left = 496
    Top = 120
  end
  object pmnElemDettaglio: TPopupMenu
    Left = 480
    Top = 504
    object actAggiungiTutti: TMenuItem
      Caption = 'Aggiungi tutti'
      OnClick = actAggiungiTuttiAsyncClick
    end
    object actRimuoviTutti: TMenuItem
      Caption = 'Rimuovi tutti'
      OnClick = actRimuoviTuttiAsyncClick
    end
  end
  object pmnGrdTabella: TPopupMenu
    Left = 306
    Top = 790
    object actScaricaInExcel: TMenuItem
      Caption = 'Scarica in Excel'
      Hint = 'file_xls'
      OnClick = actScaricaInExcelClick
    end
    object actScaricaInCSV: TMenuItem
      Caption = 'Scarica in CSV'
      Hint = 'file_csv'
      OnClick = actScaricaInCSVClick
    end
  end
end
