inherited WA203FDatiMensiliPersonalizzatiDettFM: TWA203FDatiMensiliPersonalizzatiDettFM
  object meIWLabel1: TmeIWLabel [0]
    Left = 24
    Top = 80
    Width = 73
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lbDato'
    Caption = 'Nome dato:'
    Enabled = True
  end
  object meIWDBEdit1: TmeIWDBEdit [1]
    Left = 24
    Top = 102
    Width = 249
    Height = 21
    Css = 'width40chr'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'dedtDato'
    SubmitOnAsyncEvent = True
    TabOrder = 0
    AutoEditable = True
    DataField = 'NomeCampo'
    PasswordPrompt = False
  end
  inherited IWFrameRegion: TIWRegion
    object lblDato: TmeIWLabel
      Left = 16
      Top = 72
      Width = 28
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDato'
      Caption = 'Dato'
      Enabled = True
    end
    object dedtDato: TmeIWDBEdit
      Left = 16
      Top = 94
      Width = 249
      Height = 21
      Css = 'width25chr'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'dedtDato'
      SubmitOnAsyncEvent = True
      TabOrder = 0
      AutoEditable = True
      DataField = 'Dato'
      PasswordPrompt = False
    end
    object lblCodiceVoce: TmeIWLabel
      Left = 16
      Top = 136
      Width = 74
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblCodiceVoce'
      Caption = 'Codice voce'
      Enabled = True
    end
    object dedtOrdinamento: TmeIWDBEdit
      Left = 136
      Top = 158
      Width = 89
      Height = 21
      Css = 'width7chr'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'dedtOrdinamento'
      SubmitOnAsyncEvent = True
      TabOrder = 1
      AutoEditable = True
      DataField = 'ORDINAMENTO'
      PasswordPrompt = False
    end
    object lblOrdinamento: TmeIWLabel
      Left = 136
      Top = 136
      Width = 81
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblOrdinamento'
      Caption = 'Ordinamento'
      Enabled = True
    end
    object desdDesc: TmeIWDBEdit
      Left = 320
      Top = 94
      Width = 249
      Height = 21
      Css = 'width45chr'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'desdDesc'
      SubmitOnAsyncEvent = True
      TabOrder = 2
      AutoEditable = True
      DataField = 'Descrizione'
      PasswordPrompt = False
    end
    object lblDescrizione: TmeIWLabel
      Left = 320
      Top = 72
      Width = 71
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDescrizione'
      Caption = 'Descrizione'
      Enabled = True
    end
    object lblEspressione: TmeIWLabel
      Left = 320
      Top = 136
      Width = 74
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblEspressione'
      Caption = 'Espressione'
      Enabled = True
    end
    object dmemoEspressione: TmeIWDBMemo
      Left = 320
      Top = 158
      Width = 249
      Height = 51
      Css = 'width45chr'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BGColor = clNone
      Editable = False
      Font.Color = clNone
      Font.Size = 10
      Font.Style = []
      InvisibleBorder = False
      HorizScrollBar = False
      VertScrollBar = True
      Required = False
      TabOrder = 3
      SubmitOnAsyncEvent = True
      AutoEditable = True
      DataField = 'ESPRESSIONE'
      FriendlyName = 'dmemoEspressione'
    end
    object lblDescVocePaghe: TmeIWLabel
      Left = 16
      Top = 193
      Width = 53
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblDescVocePaghe'
      Caption = '_______'
      Enabled = True
    end
    object lblSelezioniAnagrafiche: TmeIWLabel
      Left = 16
      Top = 232
      Width = 138
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblSelezioniAnagrafiche'
      Caption = 'Selezione anagrafiche'
      Enabled = True
    end
    object dedtSelezioneAnagrafiche: TmeIWDBEdit
      Left = 16
      Top = 254
      Width = 553
      Height = 21
      Css = 'width90chr'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'dedtSelezioneAnagrafiche'
      SubmitOnAsyncEvent = True
      TabOrder = 4
      AutoEditable = True
      DataField = 'SELEZIONE_ANAGRAFE'
      PasswordPrompt = False
    end
    object cmbVocePaghe: TMedpIWMultiColumnComboBox
      Left = 14
      Top = 158
      Width = 99
      Height = 25
      Css = 'medpMultiColumnCombo'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'cmbVocePaghe'
      SubmitOnAsyncEvent = True
      TabOrder = 5
      OnAsyncChange = cmbVocePagheAsyncChange
      PopUpHeight = 15
      PopUpWidth = 0
      Text = ''
      ColCount = 2
      Items = <>
      CustomElement = True
      ColumnTitles.Visible = False
      medpAutoResetItems = True
      CssInputText = 'medpMultiColumnComboBoxInput width10chr'
      LookupColumn = 0
      CodeColumn = 0
    end
    object drgpTipo: TmeIWDBRadioGroup
      Left = 586
      Top = 94
      Width = 86
      Height = 115
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      SubmitOnAsyncEvent = True
      RawText = False
      TrimValues = True
      AutoEditable = True
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      Layout = glVertical
      DataField = 'TIPO'
      FriendlyName = 'drgpTipo'
      Values.Strings = (
        'D'
        'O'
        'N'
        'S')
      Items.Strings = (
        'Data'
        'Ore'
        'Numero'
        'Stringa')
      TabOrder = 6
    end
    object lblTipo: TmeIWLabel
      Left = 586
      Top = 72
      Width = 27
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      FriendlyName = 'lblTipo'
      Caption = 'Tipo'
      Enabled = True
    end
    object imgApplicaAnagrafiche: TmeIWImageFile
      Left = 586
      Top = 254
      Width = 22
      Height = 21
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BorderOptions.Width = 0
      TabOrder = -1
      UseSize = False
      OnClick = imgApplicaAnagraficheClick
      Cacheable = True
      FriendlyName = 'imgApplicaAnagrafiche'
      ImageFile.Filename = 'img\btnC700SelezioneAnagrafe.png'
      medpDownloadButton = False
    end
  end
  inherited TemplateProcessor: TIWTemplateProcessorHTML
    Left = 456
    Top = 16
  end
  inherited JQuery: TIWJQueryWidget
    Left = 376
    Top = 16
  end
end
