Unit B024UADSCatanzaroIntf;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   file://C:\SVN\Sviluppo\PJServizi\B024catanzaro.wsdl
Date:     13/03/2018 11:34:50
IndySoap: V2.00-000
---------------------------------------------------------------------------}

Interface

Uses
  IdSoapDateTime,
  IdSoapRpcPacket,
  IdSoapTypeRegistry;

Type

  WSSoggetto = class;
  profiloRequest = class;
  abilitazioniSoggettoSetRequest = class;
  listaUnitaResponse = class;
  listaUnitaRequest = class;
  listaApplicativiUtenteGetResponse = class;
  listaApplicativiUtenteGetRequest = class;
  abilitazioniSoggettoGetResponse = class;
  abilitazioniSoggettoGetRequest = class;
  listaRuoliResponse = class;
  listaRuoliRequest = class;

  listaUnitaResponseArray = array of listaUnitaResponse;
  listaApplicativiUtenteGetResponseArray = array of listaApplicativiUtenteGetResponse;
  abilitazioniSoggettoGetResponseArray = array of abilitazioniSoggettoGetResponse;
  listaRuoliResponseArray = array of listaRuoliResponse;

  WSSoggetto = class (TIdBaseSoapableClass)
  Private
    Fcognome : string;
    Fnome : string;
    FcodiceFiscale : string;
    Femail : string;
    Ftelefono : string;
  Published
    property cognome : string read Fcognome write Fcognome;
    property nome : string read Fnome write Fnome;
    property codiceFiscale : string read FcodiceFiscale write FcodiceFiscale;
    property email : string read Femail write Femail;
    property telefono : string read Ftelefono write Ftelefono;
  end;

  profiloRequest = class (TIdBaseSoapableClass)
  Private
    FcodiceAmministrazione : string;
    FcodiceComponente : string;
    FcodiceRuolo : string;
    FcodiceSistema : string;
    FcodiceTipoAutorizzazione : Integer;
    FcodiceUnita : string;
    FdataDecorrenzaORevoca : string;
  Published
    property codiceAmministrazione : string read FcodiceAmministrazione write FcodiceAmministrazione;
    property codiceComponente : string read FcodiceComponente write FcodiceComponente;
    property codiceRuolo : string read FcodiceRuolo write FcodiceRuolo;
    property codiceSistema : string read FcodiceSistema write FcodiceSistema;
    property codiceTipoAutorizzazione : Integer read FcodiceTipoAutorizzazione write FcodiceTipoAutorizzazione;
    property codiceUnita : string read FcodiceUnita write FcodiceUnita;
    property dataDecorrenzaORevoca : string read FdataDecorrenzaORevoca write FdataDecorrenzaORevoca;
  end;

  abilitazioniSoggettoSetRequest = class (TIdBaseSoapableClass)
  Private
    FcodiceFiscale : string;
    Fcognome : string;
    Femail : string;
    Fnome : string;
    Fprofilo : profiloRequest;
    Ftelefono : string;
  Published
    property codiceFiscale : string read FcodiceFiscale write FcodiceFiscale;
    property cognome : string read Fcognome write Fcognome;
    property email : string read Femail write Femail;
    property nome : string read Fnome write Fnome;
    property profilo : profiloRequest read Fprofilo write Fprofilo;
    property telefono : string read Ftelefono write Ftelefono;
  end;

  listaUnitaResponse = class (TIdBaseSoapableClass)
  Private
    FcodiceUnita : string;
    FdescrizioneUnita : string;
  Published
    property codiceUnita : string read FcodiceUnita write FcodiceUnita;
    property descrizioneUnita : string read FdescrizioneUnita write FdescrizioneUnita;
  end;

  listaUnitaRequest = class (TIdBaseSoapableClass)
  Private
    FcodiceAmministrazione : string;
    FcodiceRuolo : string;
  Published
    property codiceAmministrazione : string read FcodiceAmministrazione write FcodiceAmministrazione;
    property codiceRuolo : string read FcodiceRuolo write FcodiceRuolo;
  end;

  listaApplicativiUtenteGetResponse = class (TIdBaseSoapableClass)
  Private
    Fcodice : string;
    Fdescrizione : string;
    Furl : string;
  Published
    property codice : string read Fcodice write Fcodice;
    property descrizione : string read Fdescrizione write Fdescrizione;
    property url : string read Furl write Furl;
  end;

  listaApplicativiUtenteGetRequest = class (TIdBaseSoapableClass)
  Private
    FcodiceAmministrazione : string;
    FidentificativoUtente : string;
  Published
    property codiceAmministrazione : string read FcodiceAmministrazione write FcodiceAmministrazione;
    property identificativoUtente : string read FidentificativoUtente write FidentificativoUtente;
  end;

  abilitazioniSoggettoGetResponse = class (TIdBaseSoapableClass)
  Private
    FcodiceRuolo : string;
    FcodiceTipoAutorizzazione : Integer;
    FcodiceUnita : string;
    FdataDecorrenza : TIdSoapDateTime;
    FdataScadenza : TIdSoapDateTime;
    FdescrizioneRuolo : string;
    FdescrizioneUnita : string;
  Published
    property codiceRuolo : string read FcodiceRuolo write FcodiceRuolo;
    property codiceTipoAutorizzazione : Integer read FcodiceTipoAutorizzazione write FcodiceTipoAutorizzazione;
    property codiceUnita : string read FcodiceUnita write FcodiceUnita;
    property dataDecorrenza : TIdSoapDateTime read FdataDecorrenza write FdataDecorrenza;
    property dataScadenza : TIdSoapDateTime read FdataScadenza write FdataScadenza;
    property descrizioneRuolo : string read FdescrizioneRuolo write FdescrizioneRuolo;
    property descrizioneUnita : string read FdescrizioneUnita write FdescrizioneUnita;
  end;

  abilitazioniSoggettoGetRequest = class (TIdBaseSoapableClass)
  Private
    FcodFiscaleSoggettoDaAbilitare : string;
    FcodiceAmministrazione : string;
    FcodiceComponente : string;
    FcodiceSistema : string;
  Published
    property codFiscaleSoggettoDaAbilitare : string read FcodFiscaleSoggettoDaAbilitare write FcodFiscaleSoggettoDaAbilitare;
    property codiceAmministrazione : string read FcodiceAmministrazione write FcodiceAmministrazione;
    property codiceComponente : string read FcodiceComponente write FcodiceComponente;
    property codiceSistema : string read FcodiceSistema write FcodiceSistema;
  end;

  listaRuoliResponse = class (TIdBaseSoapableClass)
  Private
    FareeAccessibili : string;
    FcodiceRuolo : string;
    FdescrizioneRuolo : string;
  Published
    property areeAccessibili : string read FareeAccessibili write FareeAccessibili;
    property codiceRuolo : string read FcodiceRuolo write FcodiceRuolo;
    property descrizioneRuolo : string read FdescrizioneRuolo write FdescrizioneRuolo;
  end;

  listaRuoliRequest = class (TIdBaseSoapableClass)
  Private
    FcodiceComponente : string;
  Published
    property codiceComponente : string read FcodiceComponente write FcodiceComponente;
  end;


type
  {Soap Address for this Interface: http://servername/ProfilazioneUtenteService/ProfilazioneUtenteService}
  IProfilazioneUtente = Interface (IIdSoapInterface) ['{9DCA999D-9BA1-4639-AC23-F2A1DDFFC3F1}']
       {!Namespace: it.finmatica.gestioneautorizzazioni;
         Encoding: Document}
    procedure getListaRuoli(filtri : listaRuoliRequest; out ruolo : listaRuoliResponseArray); stdcall;
      {!Request: getListaRuoli; }
    procedure getAbilitazioniSoggetto(filtri : abilitazioniSoggettoGetRequest; out abilitazione : abilitazioniSoggettoGetResponseArray); stdcall;
      {!Request: getAbilitazioniSoggetto; }
    function  getListaApplicativiUtente(filtri : listaApplicativiUtenteGetRequest) : listaApplicativiUtenteGetResponseArray; stdcall;
      {!Request: getListaApplicativiUtente; }
    procedure getListaUnita(filtri : listaUnitaRequest; out unita : listaUnitaResponseArray); stdcall;
      {!Request: getListaUnita; }
    procedure setAbilitazioniSoggetto(abilitazione : abilitazioniSoggettoSetRequest); stdcall;
      {!Request: setAbilitazioniSoggetto; }
    procedure modificaAnagrafica(oldSoggetto : WSSoggetto; newSoggetto : WSSoggetto); stdcall;
      {!Request: modificaAnagrafica; }
  end;

Implementation

{$R B024UADSCatanzaroIntf.res}

Uses
  //IdSoapRTTIHelpers,
  IdSoapIntfRegistry;
  //SysUtils;


Initialization
  IdSoapRegisterType(TypeInfo(WSSoggetto));
  IdSoapRegisterType(TypeInfo(profiloRequest));
  IdSoapRegisterType(TypeInfo(abilitazioniSoggettoSetRequest));
  IdSoapRegisterType(TypeInfo(listaUnitaResponseArray), '', TypeInfo(listaUnitaResponse));
  IdSoapRegisterType(TypeInfo(listaUnitaResponse));
  IdSoapRegisterType(TypeInfo(listaUnitaRequest));
  IdSoapRegisterType(TypeInfo(listaApplicativiUtenteGetResponseArray), '', TypeInfo(listaApplicativiUtenteGetResponse));
  IdSoapRegisterType(TypeInfo(listaApplicativiUtenteGetResponse));
  IdSoapRegisterType(TypeInfo(listaApplicativiUtenteGetRequest));
  IdSoapRegisterType(TypeInfo(abilitazioniSoggettoGetResponseArray), '', TypeInfo(abilitazioniSoggettoGetResponse));
  IdSoapRegisterType(TypeInfo(abilitazioniSoggettoGetResponse));
  IdSoapRegisterType(TypeInfo(abilitazioniSoggettoGetRequest));
  IdSoapRegisterType(TypeInfo(listaRuoliResponseArray), '', TypeInfo(listaRuoliResponse));
  IdSoapRegisterType(TypeInfo(listaRuoliResponse));
  IdSoapRegisterType(TypeInfo(listaRuoliRequest));
  IdSoapRegisterInterface(TypeInfo(IProfilazioneUtente));
End.
