object W002FSQL: TW002FSQL
  Left = 0
  Top = 0
  Width = 349
  Height = 296
  ConnectionMode = cmAny
  SupportedBrowsers = [brIE, brNetscape6, brNetscape4]
  BrowserSecurityCheck = True
  Background.Fixed = False
  HandleTabs = False
  LockUntilLoaded = True
  LockOnSubmit = True
  UpdateMode = umAll
  DesignLeft = 209
  DesignTop = 111
  object btnOK: TIWButton
    Left = 44
    Top = 152
    Width = 75
    Height = 25
    Cursor = crAuto
    IW50Hint = False
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = True
    ButtonType = btButton
    Caption = 'OK'
    Color = 13160660
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnOK'
    ScriptEvents = <>
    TabOrder = 0
    OnClick = btnOKClick
  end
  object memoSQL: TIWMemo
    Left = 44
    Top = 16
    Width = 277
    Height = 121
    Cursor = crAuto
    IW50Hint = False
    ParentShowHint = False
    ShowHint = True
    ZIndex = 0
    RenderSize = True
    BGColor = clNone
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    InvisibleBorder = False
    HorizScrollBar = False
    VertScrollBar = True
    Required = False
    TabOrder = 1
    FriendlyName = 'TIWMemo1'
  end
end
