object W032FPercorsoFM: TW032FPercorsoFM
  Left = 0
  Top = 0
  Width = 569
  Height = 492
  TabOrder = 0
  object IWFrameRegion: TIWRegion
    Left = 0
    Top = 0
    Width = 569
    Height = 492
    RenderInvisibleControls = False
    OnRender = IWFrameRegionRender
    TabOrder = 0
    Align = alClient
    BorderOptions.NumericWidth = 1
    BorderOptions.BorderWidth = cbwNumeric
    BorderOptions.Style = cbsSolid
    BorderOptions.Color = clNone
    LayoutMgr = IWTemplateProcessorFrame
    OnCreate = IWFrameRegionCreate
    object btnConferma: TmeIWButton
      Left = 366
      Top = 442
      Width = 75
      Height = 25
      Css = 'pulsante'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Conferma'
      Color = clBtnFace
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'btnConferma'
      TabOrder = 0
      OnClick = btnConfermaClick
      medpDownloadButton = False
    end
    object btnAnnulla: TmeIWButton
      Left = 447
      Top = 442
      Width = 75
      Height = 25
      Hint = 'Ripristina il percorso originale della richiesta'
      Css = 'pulsante'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Annulla'
      Color = clBtnFace
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'btnConferma'
      TabOrder = 1
      OnClick = btnAnnullaClick
      medpDownloadButton = False
    end
    object lblKmTot: TmeIWLabel
      Left = 211
      Top = 366
      Width = 121
      Height = 20
      Css = 'intestazione align_right'
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Alignment = taRightJustify
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = True
      AutoSize = False
      FriendlyName = 'lblKmTot'
      Caption = 'lblKmTot'
      Enabled = True
    end
    object lblErrore: TmeIWLabel
      Left = 32
      Top = 407
      Width = 273
      Height = 16
      Css = 'segnalazione'
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      AutoSize = False
      FriendlyName = 'lblErrore'
      Caption = 'Spazio per indicazione errori'
      Enabled = True
    end
    object rgpFlagPercorso: TmeIWRadioGroup
      Left = 40
      Top = 106
      Width = 482
      Height = 25
      Cursor = crDefault
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      SubmitOnAsyncEvent = True
      RawText = False
      Editable = True
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'rgpFlagPercorso'
      ItemIndex = 0
      Items.Strings = (
        'Partenza e arrivo alla sede'
        'Partenza e/o arrivo al domicilio'
        'Altro')
      Layout = glHorizontal
      TabOrder = 2
      OnAsyncClick = rgpFlagPercorsoAsyncClick
    end
    object lblFlagPercorso: TmeIWLabel
      Left = 32
      Top = 77
      Width = 121
      Height = 24
      Css = 'intestazione'
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      HasTabOrder = False
      AutoSize = False
      FriendlyName = 'lblFlagPercorso'
      Caption = 'Percorso'
      Enabled = True
    end
    object grdPercorso: TmeIWGrid
      Left = 32
      Top = 208
      Width = 300
      Height = 145
      Css = 'grid'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      BorderColors.Color = clNone
      BorderColors.Light = clNone
      BorderColors.Dark = clNone
      BGColor = clNone
      BorderSize = 0
      BorderStyle = tfVoid
      Caption = 'grdPercorso'
      CellPadding = 0
      CellSpacing = 0
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FrameBuffer = 40
      Lines = tlNone
      OnRenderCell = grdPercorsoRenderCell
      UseFrame = False
      UseSize = False
      HeaderRowCount = 0
      CellRenderOptions = []
      FriendlyName = 'grdPercorso'
      ColumnCount = 1
      RowCount = 1
      ShowEmptyCells = True
      ShowInvisibleRows = True
      ScrollToCurrentRow = True
    end
    object cmbNuovaTappa: TMedpIWMultiColumnComboBox
      Left = 121
      Top = 159
      Width = 121
      Height = 21
      Css = 'medpMultiColumnCombo'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'cmbPartenza'
      SubmitOnAsyncEvent = True
      TabOrder = 3
      OnAsyncChange = cmbNuovaTappaAsyncChange
      PopUpHeight = 15
      PopUpWidth = 20
      Text = ''
      ColCount = 2
      Items = <>
      CustomElement = True
      ColumnTitles.Visible = False
      medpAutoResetItems = True
      CssInputText = 'medpMultiColumnComboBoxInput width30chr'
      LookupColumn = 1
      CodeColumn = 0
    end
    object lblNuovaTappa: TmeIWLabel
      Left = 32
      Top = 159
      Width = 83
      Height = 16
      Css = 'intestazione'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      ForControl = cmbNuovaTappa
      HasTabOrder = False
      FriendlyName = 'lblNuovaTappa'
      Caption = 'Nuova tappa:'
      Enabled = True
    end
    object btnNuovaTappa: TmeIWButton
      Left = 257
      Top = 159
      Width = 75
      Height = 25
      Css = 'pulsante'
      RenderSize = False
      StyleRenderOptions.RenderSize = False
      StyleRenderOptions.RenderPosition = False
      StyleRenderOptions.RenderFont = False
      StyleRenderOptions.RenderZIndex = False
      StyleRenderOptions.RenderAbsolute = False
      StyleRenderOptions.RenderPadding = False
      StyleRenderOptions.RenderBorder = False
      Caption = 'Aggiungi'
      Color = clBtnFace
      Font.Color = clNone
      Font.Enabled = False
      Font.Size = 10
      Font.Style = []
      FriendlyName = 'btnNuovaTappa'
      TabOrder = 4
      OnClick = btnNuovaTappaClick
      medpDownloadButton = False
    end
  end
  object IWTemplateProcessorFrame: TIWTemplateProcessorHTML
    TagType = ttIntraWeb
    RenderStyles = False
    Left = 56
    Top = 8
  end
  object jQVisFrame: TIWJQueryWidget
    Enabled = True
    Left = 432
    Top = 44
  end
  object jqFocus: TIWJQueryWidget
    Enabled = True
    Left = 496
    Top = 40
  end
end
