inherited W043FModPersonaleReperibile: TW043FModPersonaleReperibile
  Tag = 452
  Width = 781
  Height = 505
  HelpType = htKeyword
  HelpKeyword = 'W043P0'
  Title = '(W043) Modifica personale reperibile'
  ExplicitWidth = 781
  ExplicitHeight = 505
  DesignLeft = 8
  DesignTop = 8
  object lblDataPianificazione: TmeIWLabel [8]
    Left = 32
    Top = 135
    Width = 117
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblDataPianificazione'
    Caption = 'Data pianificazione'
    Enabled = True
  end
  object edtDataPianificazione: TmeIWEdit [9]
    Left = 225
    Top = 155
    Width = 88
    Height = 21
    Css = 'input_data_dmy'
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edtDataPianificazione'
    SubmitOnAsyncEvent = True
    TabOrder = 6
    OnAsyncChange = edtDataPianificazioneAsyncChange
    Text = 'edtDataPianificazione'
  end
  object lblFiltroDato1: TmeIWLabel [10]
    Left = 483
    Top = 158
    Width = 40
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ForControl = cmbFiltroDato1
    HasTabOrder = False
    FriendlyName = 'lblFiltroDato1'
    Caption = 'Dato 1'
    Enabled = True
  end
  object lblLegendaFiltri: TmeIWLabel [11]
    Left = 483
    Top = 131
    Width = 101
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblLegendaFiltri'
    Caption = 'Filtro dipendenti'
    Enabled = True
  end
  object lblFiltroDato2: TmeIWLabel [12]
    Left = 483
    Top = 185
    Width = 40
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ForControl = cmbFiltroDato2
    HasTabOrder = False
    FriendlyName = 'lblFiltroDato2'
    Caption = 'Dato 2'
    Enabled = True
  end
  object lblDipendente1: TmeIWLabel [13]
    Left = 18
    Top = 224
    Width = 82
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblDipendente1'
    Caption = 'Dipendente 1'
    Enabled = True
  end
  object lblDipendente2: TmeIWLabel [14]
    Left = 16
    Top = 264
    Width = 82
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblDipendente2'
    Caption = 'Dipendente 2'
    Enabled = True
  end
  object cmbDipendente1: TmeIWComboBox [15]
    Left = 106
    Top = 224
    Width = 159
    Height = 21
    Css = 'select_cour30'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = True
    OnChange = cmbDipendente1Change
    UseSize = False
    TabOrder = 7
    ItemIndex = -1
    FriendlyName = 'cmbDipendente1'
    NoSelectionText = ''
  end
  object cmbDipendente2: TmeIWComboBox [16]
    Left = 104
    Top = 264
    Width = 161
    Height = 21
    Css = 'select_cour30'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = True
    OnChange = cmbDipendente2Change
    UseSize = False
    TabOrder = 8
    ItemIndex = -1
    FriendlyName = 'cmbDipendente2'
    NoSelectionText = ''
  end
  object grdTurniDip1: TmedpIWDBGrid [17]
    Left = 16
    Top = 304
    Width = 721
    Height = 73
    Css = 'grid'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderBorder = False
    BorderColors.Color = clWebWHITE
    BorderColors.Light = clWebWHITE
    BorderColors.Dark = clWebWHITE
    BGColor = clNone
    BorderSize = 0
    BorderStyle = tfVoid
    CellPadding = 0
    CellSpacing = 0
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FrameBuffer = 40
    Lines = tlAll
    Summary = 'Pianificazione turni primo dipendente'
    UseFrame = False
    UseSize = False
    HeaderRowCount = 0
    CellRenderOptions = []
    ScrollToCurrentRow = False
    Columns = <>
    DataSource = dsrTurniDipDa
    FooterRowCount = 0
    FriendlyName = 'grdTurniDip1'
    FromStart = True
    HighlightColor = clNone
    HighlightRows = False
    Options = [dgShowTitles]
    RefreshMode = rmAutomatic
    RowLimit = 0
    RollOver = False
    RowClick = True
    RollOverColor = clNone
    RowHeaderColor = clNone
    RowAlternateColor = clNone
    RowCurrentColor = clNone
    TabOrder = -1
    medpTipoContatore = 'P'
    medpRighePagina = -1
    medpBrowse = True
    medpRowSelect = False
    medpEditMultiplo = False
    medpFixedColumns = 0
    medpComandiCustom = False
    medpComandiEdit = False
    medpComandiInsert = False
    medpComandoDelete = False
    OnAfterCaricaCDS = grdTurniDip1AfterCaricaCDS
  end
  object grdTurniDip2: TmedpIWDBGrid [18]
    Left = 16
    Top = 383
    Width = 721
    Height = 74
    Css = 'grid'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderBorder = False
    BorderColors.Color = clWebWHITE
    BorderColors.Light = clWebWHITE
    BorderColors.Dark = clWebWHITE
    BGColor = clNone
    BorderSize = 0
    BorderStyle = tfVoid
    CellPadding = 0
    CellSpacing = 0
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FrameBuffer = 40
    Lines = tlAll
    Summary = 'Pianificazione turni secondo dipendente'
    UseFrame = False
    UseSize = False
    HeaderRowCount = 0
    CellRenderOptions = []
    ScrollToCurrentRow = False
    Columns = <>
    DataSource = dsrTurniDipA
    FooterRowCount = 0
    FriendlyName = 'grdTurniDip2'
    FromStart = True
    HighlightColor = clNone
    HighlightRows = False
    Options = [dgShowTitles]
    RefreshMode = rmAutomatic
    RowLimit = 0
    RollOver = False
    RowClick = True
    RollOverColor = clNone
    RowHeaderColor = clNone
    RowAlternateColor = clNone
    RowCurrentColor = clNone
    TabOrder = -1
    medpTipoContatore = 'P'
    medpRighePagina = -1
    medpBrowse = True
    medpRowSelect = False
    medpEditMultiplo = False
    medpFixedColumns = 0
    medpComandiCustom = False
    medpComandiEdit = False
    medpComandiInsert = False
    medpComandoDelete = False
    OnAfterCaricaCDS = grdTurniDip2AfterCaricaCDS
  end
  object lblInfoLimitiData: TmeIWLabel [19]
    Left = 32
    Top = 179
    Width = 165
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblInfoLimitiData'
    Caption = 'Info limiti data - a runtime'
    Enabled = True
  end
  object lblIndicareData: TmeIWLabel [20]
    Left = 34
    Top = 157
    Width = 207
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblIndicareData'
    Caption = 'Indicare la data di pianificazione:'
    Enabled = True
  end
  object btnHdnLeggiPianif: TmeIWButton [21]
    Left = 203
    Top = 179
    Width = 198
    Height = 25
    Css = 'pulsante'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Caption = 'Nascosto - Leggi pianificazione'
    Color = clBtnFace
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'btnHdnLeggiPianif'
    TabOrder = 9
    OnClick = btnHdnLeggiPianifClick
    medpDownloadButton = False
  end
  object cmbFiltroDato1: TMedpIWMultiColumnComboBox [22]
    Left = 529
    Top = 153
    Width = 92
    Height = 21
    Css = 'medpMultiColumnCombo'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'cmbFiltroDato1'
    SubmitOnAsyncEvent = True
    TabOrder = 10
    PopUpHeight = 15
    PopUpWidth = 0
    Text = ''
    ColCount = 2
    Items = <>
    ColumnTitles.Visible = False
    OnChange = cmbFiltroDato1Change
    medpAutoResetItems = True
    CssInputText = 'medpMultiColumnComboBoxInput width10chr'
    LookupColumn = 0
    CodeColumn = 0
  end
  object cmbFiltroDato2: TMedpIWMultiColumnComboBox [23]
    Left = 529
    Top = 180
    Width = 92
    Height = 21
    Css = 'medpMultiColumnCombo'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'cmbFiltroDato1'
    SubmitOnAsyncEvent = True
    TabOrder = 11
    PopUpHeight = 15
    PopUpWidth = 0
    Text = ''
    ColCount = 2
    Items = <>
    ColumnTitles.Visible = False
    OnChange = cmbFiltroDato2Change
    medpAutoResetItems = True
    CssInputText = 'medpMultiColumnComboBoxInput width10chr'
    LookupColumn = 0
    CodeColumn = 0
  end
  object lblFiltroDato1Desc: TmeIWLabel [24]
    Left = 643
    Top = 158
    Width = 112
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblFiltroDato1Desc'
    Caption = 'lblFiltroDato1Desc'
    Enabled = True
  end
  object lblFiltroDato2Desc: TmeIWLabel [25]
    Left = 643
    Top = 185
    Width = 112
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblFiltroDato2Desc'
    Caption = 'lblFiltroDato2Desc'
    Enabled = True
  end
  object lblFiltroAreaSquadra: TmeIWLabel [26]
    Left = 483
    Top = 207
    Width = 34
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    ForControl = cmbFiltroAreaSquadra
    HasTabOrder = False
    FriendlyName = 'lblFiltroAreaSquadra'
    Caption = 'Area '
    Enabled = True
  end
  object cmbFiltroAreaSquadra: TMedpIWMultiColumnComboBox [27]
    Left = 529
    Top = 207
    Width = 108
    Height = 21
    Css = 'medpMultiColumnCombo'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'cmbFiltroAreaSquadra'
    SubmitOnAsyncEvent = True
    TabOrder = 12
    PopUpHeight = 15
    PopUpWidth = 0
    Text = ''
    ColCount = 2
    Items = <>
    ColumnTitles.Visible = False
    OnChange = cmbFiltroAreaSquadraChange
    medpAutoResetItems = True
    CssInputText = 'medpMultiColumnComboBoxInput width20chr'
    LookupColumn = 0
    CodeColumn = 0
  end
  object lblFiltroAreaSquadraDesc: TmeIWLabel [28]
    Left = 643
    Top = 212
    Width = 126
    Height = 16
    Css = 'intestazione'
    RenderSize = False
    StyleRenderOptions.RenderSize = False
    StyleRenderOptions.RenderPosition = False
    StyleRenderOptions.RenderFont = False
    StyleRenderOptions.RenderZIndex = False
    StyleRenderOptions.RenderAbsolute = False
    StyleRenderOptions.RenderPadding = False
    StyleRenderOptions.RenderBorder = False
    Font.Color = clNone
    Font.Enabled = False
    Font.Size = 10
    Font.Style = []
    HasTabOrder = False
    FriendlyName = 'lblFiltroAreaSquadraDesc'
    Caption = 'lblAreaSquadraDesc'
    Enabled = True
  end
  object cdsTurniDipDa: TClientDataSet
    Aggregates = <>
    Params = <>
    Left = 672
    Top = 320
  end
  object dsrTurniDipDa: TDataSource
    DataSet = cdsTurniDipDa
    Left = 592
    Top = 320
  end
  object cdsTurniDipA: TClientDataSet
    Aggregates = <>
    Params = <>
    Left = 672
    Top = 408
  end
  object dsrTurniDipA: TDataSource
    DataSet = cdsTurniDipA
    Left = 592
    Top = 408
  end
end
